export enum ActionTypes {
  AUTHED_USER = 'AUTHED_USER',
  UPDATE_NOTIFICATION = 'UPDATE_NOTIFICATION',
  GET_NOTIFICATIONS = 'GET_NOTIFICATIONS',
  LANGUAGE = 'LANGUAGE',
  CHOOSE_LANGUAGE = 'CHOOSE_LANGUAGE'
}
